/* -----------------------------------------------------------------------------
   ZONES — 10 buckets arranged on a 16:9 canvas.
   Row 1 (top): origin / description of soils
   Row 2 (mid): the three fundamental sciences
   Row 3      : applied (plants, management, anthropogenic)
   Row 4 (bot): context (environment, society)
   ---------------------------------------------------------------------------*/
const ZONES = [
  { id:"z1",  color:"var(--c-z1)",  bbox:[0.02,0.04,0.46,0.20],
    fr:"Pédogenèse &amp; genèse des sols", en:"Pedogenesis &amp; Soil Genesis", img:"afes_z1_pedogenesis.png", comp:"folio" },
  { id:"z2",  color:"var(--c-z2)",  bbox:[0.52,0.04,0.46,0.20],
    fr:"Morphologie, classification &amp; cartographie", en:"Morphology, Classification &amp; Mapping", img:"afes_z2_morphology.png", comp:"folio" },

  { id:"z3",  color:"var(--c-z3)",  bbox:[0.02,0.28,0.30,0.24],
    fr:"Physique &amp; mécanique du sol", en:"Soil Physics &amp; Mechanics", img:"afes_z3_physics.png", comp:"plate" },
  { id:"z4",  color:"var(--c-z4)",  bbox:[0.35,0.28,0.30,0.24],
    fr:"Chimie &amp; biogéochimie", en:"Soil Chemistry &amp; Biogeochemistry", img:"afes_z4_chemistry.png", comp:"plate" },
  { id:"z5",  color:"var(--c-z5)",  bbox:[0.68,0.28,0.30,0.24],
    fr:"Biologie, microbiologie &amp; écologie", en:"Soil Biology, Microbiology &amp; Ecology", img:"afes_z5_biology.png", comp:"plate" },

  { id:"z6",  color:"var(--c-z6)",  bbox:[0.02,0.56,0.30,0.20],
    fr:"Sols &amp; plantes (édaphologie)", en:"Soils &amp; Plants (Edaphology)", img:"afes_z6_edaphology.png", comp:"folio" },
  { id:"z7",  color:"var(--c-z7)",  bbox:[0.35,0.56,0.30,0.20],
    fr:"Gestion &amp; usage des sols", en:"Soil Management &amp; Land Use", img:"afes_z7_management.png", comp:"folio" },
  { id:"z8",  color:"var(--c-z8)",  bbox:[0.68,0.56,0.30,0.20],
    fr:"Sols anthropogéniques", en:"Anthropogenic Soils", img:"afes_z8_anthropogenic.png", comp:"folio" },

  { id:"z9",  color:"var(--c-z9)",  bbox:[0.02,0.80,0.46,0.18],
    fr:"Sols, environnement &amp; climat", en:"Soils, Environment &amp; Climate", img:"afes_z9_environment.png", comp:"folio" },
  { id:"z10", color:"var(--c-z10)", bbox:[0.52,0.80,0.46,0.18],
    fr:"Sols &amp; société · frontières", en:"Soils &amp; Society · Frontiers", img:"afes_z10_society.png", comp:"folio" },
];

/* -----------------------------------------------------------------------------
   NODES — each discipline with bilingual definition, sub-branches and neighbors.
   ---------------------------------------------------------------------------*/
const NODES = [
  /* ====================== Z1 — PÉDOGENÈSE ====================== */
  { id:"factors", zone:"z1",
    fr:"Facteurs de formation (CLORPT)", en:"Soil-forming factors (CLORPT)",
    defFr:"Les cinq grands facteurs de Jenny : climat, organismes, relief, roche-mère, temps (CLORPT) — enrichis aujourd'hui par les cadres SCORPAN et STEP-AWBH.",
    defEn:"Jenny's five factors: climate, organisms, relief, parent material, time (CLORPT) — extended by modern frameworks such as SCORPAN and STEP-AWBH.",
    subs:[ ["Climat","Climate"], ["Organismes","Organisms"], ["Relief","Relief / topography"],
           ["Roche-mère","Parent material"], ["Temps","Time"], ["SCORPAN / STEP-AWBH","SCORPAN / STEP-AWBH"] ],
    neighbors:["weathering","pedogenic-processes","soil-evolution","mapping-dsm","critical-zone"] },
  { id:"weathering", zone:"z1",
    fr:"Altération", en:"Weathering",
    defFr:"Décomposition physique, chimique et biologique de la roche-mère — le premier pas vers un sol.",
    defEn:"Physical, chemical and biological breakdown of parent material — the first step towards a soil.",
    subs:[ ["Altération physique","Physical weathering"], ["Altération chimique","Chemical weathering"],
           ["Altération biologique","Biological weathering"], ["Podzolisation / lessivage","Podzolisation / eluviation"] ],
    neighbors:["factors","pedogenic-processes","mineralogy","critical-zone"] },
  { id:"pedogenic-processes", zone:"z1",
    fr:"Processus pédogénétiques", en:"Pedogenic processes",
    defFr:"Mécanismes qui organisent le sol : brunification, podzolisation, rubéfaction, gleyification, vertisolisation…",
    defEn:"The mechanisms that organise a soil: brunification, podzolisation, rubefaction, gleying, vertisolisation…",
    subs:[ ["Brunification","Brunification"], ["Podzolisation","Podzolisation"], ["Rubéfaction","Rubefaction"],
           ["Gleyification","Gleying"], ["Vertisolisation","Vertisolisation"], ["Translocation d'argiles","Clay translocation"] ],
    neighbors:["factors","weathering","horizons","paleopedology","mineralogy"] },
  { id:"horizons", zone:"z1",
    fr:"Horizons &amp; profil", en:"Horizons &amp; soil profile",
    defFr:"L'organisation verticale du sol en horizons O, A, E, B, C, R — la \"carte d'identité\" d'un sol.",
    defEn:"The vertical organisation of a soil into horizons O, A, E, B, C, R — the fingerprint of any soil profile.",
    subs:[ ["Horizons génétiques","Genetic horizons"], ["Symboles majeurs &amp; suffixes","Master horizons &amp; subscripts"],
           ["Horizons diagnostiques","Diagnostic horizons"] ],
    neighbors:["morphology","classification","micromorphology","pedogenic-processes"] },
  { id:"paleopedology", zone:"z1",
    fr:"Paléopédologie", en:"Paleopedology",
    defFr:"Étude des paléosols — archives des climats, paysages et écosystèmes passés.",
    defEn:"The study of paleosols — archives of past climates, landscapes and ecosystems.",
    subs:[ ["Paléosols","Paleosols"], ["Reconstruction climatique","Paleoclimate reconstruction"],
           ["Stratigraphie pédologique","Pedostratigraphy"] ],
    neighbors:["pedogenic-processes","archaeology","micromorphology","soil-evolution"] },
  { id:"anthropogenesis", zone:"z1",
    fr:"Anthropogenèse des sols", en:"Soil anthropogenesis",
    defFr:"Formation et transformation des sols sous l'action humaine directe (agriculture, terrassement, dépôts) — conduit aux anthroposols et technosols.",
    defEn:"Soil formation and transformation driven directly by humans (farming, earthworks, deposits) — yielding anthrosols and technosols.",
    subs:[ ["Anthroposols","Anthrosols"], ["Terra preta","Terra preta"], ["Sols archéologiques","Archaeological soils"],
           ["Technosols","Technosols"] ],
    neighbors:["urban-soils","technosols","archaeology","ethnopedology"] },
  { id:"soil-evolution", zone:"z1",
    fr:"Évolution &amp; vitesse de formation", en:"Soil evolution &amp; formation rates",
    defFr:"Dynamiques longues : vitesses d'altération, temps de résidence, bilans de masse et équilibres entre genèse et érosion.",
    defEn:"Long-term dynamics: weathering rates, residence times, mass balance and the balance between genesis and erosion.",
    subs:[ ["Vitesses de formation","Formation rates"], ["Bilan de masse","Mass balance"],
           ["Équilibre genèse-érosion","Production vs. erosion"] ],
    neighbors:["factors","weathering","critical-zone","erosion"] },

  /* ====================== Z2 — MORPHO / CLASSIFICATION / CARTO ====================== */
  { id:"morphology", zone:"z2",
    fr:"Morphologie du sol", en:"Soil morphology",
    defFr:"Description visuelle et tactile sur le terrain : couleur Munsell, texture, structure, porosité, consistance.",
    defEn:"Hands-on field description: Munsell colour, texture, structure, porosity, consistency.",
    subs:[ ["Couleur Munsell","Munsell colour"], ["Texture","Texture"], ["Structure","Structure"],
           ["Porosité &amp; pores","Porosity &amp; pores"], ["Traits pédologiques","Pedological features"] ],
    neighbors:["micromorphology","survey","classification","horizons"] },
  { id:"micromorphology", zone:"z2",
    fr:"Micromorphologie", en:"Soil micromorphology",
    defFr:"Observation de lames minces de sol au microscope pour décrire la microstructure et les traits pédogénétiques fins.",
    defEn:"Microscope observation of soil thin sections to describe microstructure and fine pedogenic features.",
    subs:[ ["Lames minces","Thin sections"], ["Microstructure","Microstructure"], ["Traits micropédologiques","Micropedogenic features"] ],
    neighbors:["morphology","pedogenic-processes","paleopedology","mineralogy"] },
  { id:"survey", zone:"z2",
    fr:"Prospection pédologique", en:"Soil survey",
    defFr:"Reconnaissance systématique sur le terrain — fosses, sondages, prélèvements, descriptions — au cœur de toute connaissance territoriale du sol.",
    defEn:"Systematic field reconnaissance — pits, augers, sampling, descriptions — backbone of any territorial soil knowledge.",
    subs:[ ["Fosses pédologiques","Soil pits"], ["Sondages à la tarière","Auger sampling"],
           ["Échantillonnage","Sampling design"], ["Cartes de sondages","Observation maps"] ],
    neighbors:["morphology","classification","cartography","dsm","pedometrics"] },
  { id:"classification", zone:"z2",
    fr:"Classification des sols", en:"Soil classification",
    defFr:"Systèmes internationaux et nationaux qui organisent la diversité des sols : WRB, Soil Taxonomy (USDA), Référentiel pédologique (FR).",
    defEn:"International and national systems that organise soil diversity: WRB, USDA Soil Taxonomy, and France's Référentiel Pédologique.",
    subs:[ ["WRB (FAO/IUSS)","WRB"], ["Soil Taxonomy (USDA)","USDA Soil Taxonomy"],
           ["Référentiel pédologique (RP)","French Référentiel Pédologique"], ["Classifications nationales","National systems"] ],
    neighbors:["morphology","survey","horizons","ethnopedology"] },
  { id:"cartography", zone:"z2",
    fr:"Cartographie des sols", en:"Soil cartography",
    defFr:"Représentation spatiale des sols et de leurs propriétés à différentes échelles — du 1:10 000 communal au 1:1 000 000 national.",
    defEn:"Spatial representation of soils and soil properties at scales from the parcel (1:10 000) to the continent (1:1 000 000).",
    subs:[ ["Cartes des sols","Soil maps"], ["Légendes &amp; typologies","Legend design"],
           ["Échelles cartographiques","Mapping scales"], ["Bases de données sols","Soil databases"] ],
    neighbors:["survey","dsm","pedometrics","remote-sensing"] },
  { id:"dsm", zone:"z2",
    fr:"Cartographie numérique (DSM)", en:"Digital soil mapping (DSM)",
    defFr:"Prédiction spatiale des sols par modèles (SCORPAN) à partir de covariables environnementales, imagerie et apprentissage machine.",
    defEn:"Model-based spatial prediction of soils (SCORPAN) using environmental covariates, imagery and machine learning.",
    subs:[ ["Cadre SCORPAN","SCORPAN framework"], ["Apprentissage machine","Machine learning"],
           ["Covariables environnementales","Environmental covariates"], ["Évaluation numérique des sols","Digital soil assessment"] ],
    neighbors:["pedometrics","remote-sensing","cartography","modeling","soil-security"] },
  { id:"pedometrics", zone:"z2",
    fr:"Pédométrie", en:"Pedometrics",
    defFr:"Application des statistiques et de la géostatistique aux sols : variabilité spatiale, incertitude, inférence.",
    defEn:"Statistical and geostatistical analysis of soils: spatial variability, uncertainty and inference.",
    subs:[ ["Géostatistique","Geostatistics"], ["Krigeage","Kriging"], ["Incertitudes","Uncertainty"],
           ["Plans d'échantillonnage","Sampling design"] ],
    neighbors:["dsm","cartography","modeling","metrology"] },
  { id:"remote-sensing", zone:"z2",
    fr:"Télédétection &amp; spectroscopie", en:"Remote sensing &amp; spectroscopy",
    defFr:"Observation des sols par satellites, drones et capteurs proches : humidité, MO, salinité, signatures spectrales (Vis-NIR, MIR).",
    defEn:"Soil observation from satellites, drones and proximal sensors: moisture, SOM, salinity, and Vis-NIR / MIR spectra.",
    subs:[ ["Imagerie satellite","Satellite imagery"], ["Drones &amp; UAV","UAV platforms"],
           ["Spectroscopie Vis-NIR &amp; MIR","Vis-NIR &amp; MIR spectroscopy"], ["Géophysique proche-surface","Near-surface geophysics"] ],
    neighbors:["dsm","cartography","metrology","modeling","salinity"] },

  /* ====================== Z3 — PHYSIQUE & MÉCANIQUE ====================== */
  { id:"physical-props", zone:"z3",
    fr:"Propriétés physiques", en:"Physical properties",
    defFr:"Masse volumique, porosité, densité apparente, texture granulométrique — les paramètres de base du sol physique.",
    defEn:"Bulk density, porosity, particle density, grain-size texture — the physical baseline of a soil.",
    subs:[ ["Densité apparente / réelle","Bulk / particle density"], ["Porosité","Porosity"],
           ["Granulométrie","Particle-size distribution"] ],
    neighbors:["structure","pedotransfer","metrology","pedogenic-processes"] },
  { id:"structure", zone:"z3",
    fr:"Structure &amp; agrégation", en:"Structure &amp; aggregation",
    defFr:"Formation, stabilité et géométrie des agrégats — architecture poreuse du sol et habitat des organismes.",
    defEn:"Formation, stability and geometry of soil aggregates — porous architecture and microbial habitat.",
    subs:[ ["Agrégats","Aggregates"], ["Stabilité structurale","Aggregate stability"],
           ["Porosité fonctionnelle","Functional porosity"], ["Battance","Surface crusting"] ],
    neighbors:["physical-props","tillage","som","microbio"] },
  { id:"hydrology", zone:"z3",
    fr:"Hydrologie du sol", en:"Soil hydrology",
    defFr:"Infiltration, rétention, drainage, écoulements préférentiels : le sol comme réservoir et régulateur de l'eau.",
    defEn:"Infiltration, retention, drainage, preferential flow: the soil as water reservoir and regulator.",
    subs:[ ["Infiltration","Infiltration"], ["Ruissellement","Runoff"], ["Écoulements préférentiels","Preferential flow"],
           ["Drainage","Drainage"] ],
    neighbors:["retention","structure","wetlands","modeling","irrigation"] },
  { id:"retention", zone:"z3",
    fr:"Rétention &amp; potentiel hydrique (pF)", en:"Water retention &amp; matric potential (pF)",
    defFr:"Courbes de rétention, potentiel matriciel, capillarité — comment le sol retient et cède l'eau aux plantes.",
    defEn:"Retention curves, matric potential, capillarity — how soils hold and release water to plants.",
    subs:[ ["Courbe de rétention (pF)","Retention curve (pF)"], ["Capacité au champ","Field capacity"],
           ["Point de flétrissement","Wilting point"], ["Capillarité","Capillarity"] ],
    neighbors:["hydrology","pedotransfer","physical-props","spac","plant-nutrition"] },
  { id:"thermal", zone:"z3",
    fr:"Propriétés thermiques", en:"Thermal properties",
    defFr:"Transfert et stockage de chaleur — régime thermique et conséquences écologiques et climatiques.",
    defEn:"Heat transfer and storage — the thermal regime and its ecological and climatic consequences.",
    subs:[ ["Conductivité thermique","Thermal conductivity"], ["Régime thermique","Thermal regime"],
           ["Pergélisol / gel","Permafrost / freezing"] ],
    neighbors:["hydrology","cryosols","climate-feedback"] },
  { id:"aeration", zone:"z3",
    fr:"Aération &amp; gaz du sol", en:"Soil aeration &amp; gases",
    defFr:"Diffusion des gaz (O₂, CO₂, N₂O, CH₄), conditions redox et émissions de gaz à effet de serre.",
    defEn:"Gas diffusion (O₂, CO₂, N₂O, CH₄), redox conditions and greenhouse-gas emissions.",
    subs:[ ["Diffusion des gaz","Gas diffusion"], ["Anaérobie / hydromorphie","Anaerobic / hydromorphy"],
           ["Émissions GES","Greenhouse-gas emissions"] ],
    neighbors:["hydrology","redox","wetlands","carbon-climate"] },
  { id:"mechanics", zone:"z3",
    fr:"Mécanique des sols &amp; compaction", en:"Soil mechanics &amp; compaction",
    defFr:"Résistance, cisaillement, plasticité, compaction sous machines — à l'interface agronomie / génie civil.",
    defEn:"Strength, shear, plasticity, machinery compaction — at the interface of agronomy and civil engineering.",
    subs:[ ["Compaction","Compaction"], ["Cisaillement","Shear strength"], ["Plasticité (Atterberg)","Plasticity (Atterberg)"],
           ["Portance","Bearing capacity"] ],
    neighbors:["structure","tillage","geotech","urban-soils"] },
  { id:"shrink-swell", zone:"z3",
    fr:"Retrait-gonflement", en:"Shrink-swell behaviour",
    defFr:"Variation de volume des sols argileux — fissuration, pédoturbation (vertisolisation), enjeux géotechniques majeurs.",
    defEn:"Volume change in clay soils — cracking, pedoturbation (vertisolisation) and major geotechnical hazards.",
    subs:[ ["Argiles gonflantes","Swelling clays"], ["Vertisols","Vertisols"],
           ["Fissuration","Cracking"], ["Aléa bâtiment","Building hazard"] ],
    neighbors:["mechanics","clay","geotech","pedogenic-processes"] },
  { id:"pedotransfer", zone:"z3",
    fr:"Fonctions de pédotransfert (PTF)", en:"Pedotransfer functions (PTFs)",
    defFr:"Relations empiriques reliant des propriétés mesurables simples aux propriétés complexes (hydriques, mécaniques) pour modéliser le sol.",
    defEn:"Empirical relationships linking simple measurements to complex (hydraulic, mechanical) properties for soil modelling.",
    subs:[ ["PTF hydrauliques","Hydraulic PTFs"], ["PTF mécaniques","Mechanical PTFs"],
           ["Apprentissage machine","Machine learning"] ],
    neighbors:["retention","modeling","pedometrics","metrology"] },

  /* ====================== Z4 — CHIMIE & BIOGÉOCHIMIE ====================== */
  { id:"chemistry", zone:"z4",
    fr:"Chimie du sol", en:"Soil chemistry",
    defFr:"Composition, réactions, équilibres — majeurs et traces dans la phase solide et en solution.",
    defEn:"Composition, reactions and equilibria — major and trace elements in solid and solution phases.",
    subs:[ ["Composition élémentaire","Elemental composition"], ["Solution du sol","Soil solution"],
           ["Équilibres","Chemical equilibria"] ],
    neighbors:["physico-chemistry","mineralogy","biogeochem","fertility"] },
  { id:"physico-chemistry", zone:"z4",
    fr:"Physico-chimie &amp; surfaces", en:"Physico-chemistry &amp; surfaces",
    defFr:"Interfaces solide-solution : charge, adsorption, CEC, complexation, colloïdes.",
    defEn:"Solid-solution interfaces: charge, adsorption, CEC, complexation, colloids.",
    subs:[ ["Charge de surface","Surface charge"], ["CEC / AEC","CEC / AEC"],
           ["Adsorption","Adsorption"], ["Colloïdes","Colloids"] ],
    neighbors:["chemistry","clay","mineralogy","metals"] },
  { id:"mineralogy", zone:"z4",
    fr:"Minéralogie du sol", en:"Soil mineralogy",
    defFr:"Minéraux primaires et secondaires : oxydes de Fe/Al, carbonates, silicates, phosphates — et leur rôle pédogénétique.",
    defEn:"Primary and secondary minerals: Fe/Al oxides, carbonates, silicates, phosphates — and their pedogenic role.",
    subs:[ ["Oxydes Fe/Al","Fe/Al oxides"], ["Carbonates","Carbonates"], ["Minéraux primaires","Primary minerals"],
           ["Minéraux secondaires","Secondary minerals"] ],
    neighbors:["clay","chemistry","pedogenic-processes","forensics"] },
  { id:"clay", zone:"z4",
    fr:"Science des argiles", en:"Clay science",
    defFr:"Phyllosilicates : structure, réactivité, gonflement, interactions organo-minérales — clé de la physico-chimie des sols.",
    defEn:"Phyllosilicates: structure, reactivity, swelling, organo-mineral interactions — keystone of soil physico-chemistry.",
    subs:[ ["Phyllosilicates","Phyllosilicates"], ["Kaolinite / smectite / illite","Kaolinite / smectite / illite"],
           ["Complexes organo-minéraux","Organo-mineral complexes"] ],
    neighbors:["mineralogy","physico-chemistry","shrink-swell","som"] },
  { id:"acidity", zone:"z4",
    fr:"Acidité &amp; pH", en:"Acidity &amp; pH",
    defFr:"Équilibres acide-base, toxicité aluminique, pouvoir tampon — déterminants majeurs de la fertilité et de la biodisponibilité.",
    defEn:"Acid-base equilibria, aluminium toxicity and buffering — central to fertility and bioavailability.",
    subs:[ ["pH du sol","Soil pH"], ["Toxicité Al","Aluminium toxicity"],
           ["Pouvoir tampon","Buffering capacity"], ["Chaulage","Liming"] ],
    neighbors:["chemistry","fertility","acid-soils","physico-chemistry"] },
  { id:"redox", zone:"z4",
    fr:"Oxydo-réduction", en:"Redox chemistry",
    defFr:"Chimie des sols anoxiques : fer, manganèse, soufre, azote — gleyification et dynamiques des zones humides.",
    defEn:"Chemistry of anoxic soils: iron, manganese, sulfur, nitrogen — gleying and wetland dynamics.",
    subs:[ ["Fer &amp; manganèse","Iron &amp; manganese"], ["Gleyification","Gleying"],
           ["Dénitrification","Denitrification"], ["Sulfures","Sulfides"] ],
    neighbors:["wetlands","aeration","biogeochem","microbio"] },
  { id:"biogeochem", zone:"z4",
    fr:"Cycles biogéochimiques", en:"Biogeochemical cycles",
    defFr:"Cycles couplés du C, N, P, S et des métaux à l'interface vivants–minéraux–solutions — fondation des services écosystémiques.",
    defEn:"Coupled cycles of C, N, P, S and metals at the biota-mineral-solution interface — the foundation of soil ecosystem services.",
    subs:[ ["Cycle du carbone","Carbon cycle"], ["Cycle de l'azote","Nitrogen cycle"],
           ["Cycle du phosphore","Phosphorus cycle"], ["Cycle du soufre","Sulfur cycle"],
           ["Cycles couplés","Coupled cycles"] ],
    neighbors:["som","microbio","carbon-climate","redox","ecosystem-services"] },
  { id:"som", zone:"z4",
    fr:"Matières organiques (MO)", en:"Soil organic matter (SOM)",
    defFr:"Origine, composition, stabilisation et dynamique des MO — cœur de la fertilité, de la structure et du cycle du carbone.",
    defEn:"Origin, composition, stabilisation and dynamics of SOM — core to fertility, structure and the carbon cycle.",
    subs:[ ["Humus &amp; humification","Humus &amp; humification"], ["Fractions de MO","SOM fractions"],
           ["Stabilisation","Stabilisation"], ["MO dissoutes","Dissolved organic matter"] ],
    neighbors:["biogeochem","biochemistry","microbio","carbon-climate","fertility","health"] },
  { id:"metals", zone:"z4",
    fr:"Éléments traces &amp; spéciation", en:"Trace elements &amp; speciation",
    defFr:"Métaux et métalloïdes : spéciation, mobilité, biodisponibilité et toxicité (Pb, Cd, As, Cu, Zn…).",
    defEn:"Metals and metalloids: speciation, mobility, bioavailability and toxicity (Pb, Cd, As, Cu, Zn…).",
    subs:[ ["Spéciation","Speciation"], ["Mobilité","Mobility"], ["Biodisponibilité","Bioavailability"],
           ["Radionucléides","Radionuclides"] ],
    neighbors:["chemistry","physico-chemistry","contamination","remediation","forensics"] },

  /* ====================== Z5 — BIOLOGIE, MICROBIO, ÉCOLOGIE ====================== */
  { id:"biology", zone:"z5",
    fr:"Biologie du sol", en:"Soil biology",
    defFr:"Ensemble du vivant dans le sol — micro-, méso- et macro-organismes — et leurs fonctions.",
    defEn:"All life in the soil — micro-, meso- and macro-organisms — and the functions they drive.",
    subs:[ ["Micro-organismes","Microorganisms"], ["Mésofaune","Mesofauna"], ["Macrofaune","Macrofauna"] ],
    neighbors:["microbio","fauna","ecology","health"] },
  { id:"microbio", zone:"z5",
    fr:"Microbiologie du sol", en:"Soil microbiology",
    defFr:"Bactéries, archées, champignons, virus : diversité, fonctions et interactions dans le sol.",
    defEn:"Bacteria, archaea, fungi and viruses: diversity, functions and interactions in soil.",
    subs:[ ["Bactéries &amp; archées","Bacteria &amp; archaea"], ["Virus du sol","Soil viruses"],
           ["Communautés microbiennes","Microbial communities"] ],
    neighbors:["fungi","biochemistry","biogeochem","rhizosphere","metagenomics"] },
  { id:"fungi", zone:"z5",
    fr:"Champignons &amp; mycorhizes", en:"Fungi &amp; mycorrhizae",
    defFr:"Champignons saprophytes, pathogènes et symbiotiques — mycorhizes arbusculaires et ectomycorhizes.",
    defEn:"Saprotrophic, pathogenic and symbiotic fungi — arbuscular and ectomycorrhizal associations.",
    subs:[ ["Saprophytes","Saprotrophs"], ["Mycorhizes arbusculaires","Arbuscular mycorrhizae"],
           ["Ectomycorhizes","Ectomycorrhizae"], ["Mycélium","Mycelial networks"] ],
    neighbors:["microbio","rhizosphere","plant-nutrition","forest-soils"] },
  { id:"fauna", zone:"z5",
    fr:"Faune du sol", en:"Soil fauna",
    defFr:"Invertébrés du sol : protozoaires, nématodes, acariens, collemboles, fourmis, vers de terre — ingénieurs du sol.",
    defEn:"Soil invertebrates — protozoa, nematodes, mites, collembola, ants, earthworms — the soil engineers.",
    subs:[ ["Vers de terre","Earthworms"], ["Collemboles / acariens","Collembola / mites"],
           ["Nématodes","Nematodes"], ["Fourmis &amp; termites","Ants &amp; termites"] ],
    neighbors:["biology","ecology","structure","som","health"] },
  { id:"ecology", zone:"z5",
    fr:"Écologie du sol", en:"Soil ecology",
    defFr:"Interactions et réseaux trophiques dans le sol ; lien entre biodiversité et fonctionnement écosystémique.",
    defEn:"Soil interactions and food webs, and the link between biodiversity and ecosystem functioning.",
    subs:[ ["Réseaux trophiques","Food webs"], ["Relations bio-fonctions","Biodiversity-function"],
           ["Succession","Ecological succession"], ["Biogéographie","Biogeography"] ],
    neighbors:["biology","biodiversity","ecosystem-services","forest-soils","wetlands"] },
  { id:"biodiversity", zone:"z5",
    fr:"Biodiversité des sols", en:"Soil biodiversity",
    defFr:"Diversité génétique, taxonomique et fonctionnelle des communautés du sol — enjeu mondial encore peu cartographié.",
    defEn:"Genetic, taxonomic and functional diversity of soil communities — a global concern still poorly mapped.",
    subs:[ ["Diversité taxonomique","Taxonomic diversity"], ["Diversité fonctionnelle","Functional diversity"],
           ["Bio-indicateurs","Bioindicators"] ],
    neighbors:["ecology","fauna","microbio","health","ecosystem-services"] },
  { id:"biochemistry", zone:"z5",
    fr:"Biochimie &amp; enzymes", en:"Biochemistry &amp; enzymes",
    defFr:"Réactions biochimiques médiées par les organismes — enzymes, métabolites, transformations de la MO.",
    defEn:"Organism-mediated biochemical reactions — enzymes, metabolites, and transformation of SOM.",
    subs:[ ["Activités enzymatiques","Enzyme activities"], ["Métabolites","Metabolites"],
           ["Dégradation MO","SOM degradation"] ],
    neighbors:["microbio","som","biogeochem","health"] },
  { id:"metagenomics", zone:"z5",
    fr:"Métagénomique &amp; 'omics'", en:"Metagenomics &amp; omics",
    defFr:"Approches moléculaires haut débit (ADN, ARN, protéines, métabolites) pour sonder le sol caché.",
    defEn:"High-throughput molecular approaches (DNA, RNA, proteins, metabolites) to probe the hidden soil.",
    subs:[ ["Métagénomique","Metagenomics"], ["Métatranscriptomique","Metatranscriptomics"],
           ["Métaprotéomique","Metaproteomics"], ["eDNA","eDNA"] ],
    neighbors:["microbio","biodiversity","biochemistry","metrology"] },
  { id:"rhizosphere", zone:"z5",
    fr:"Rhizosphère", en:"Rhizosphere",
    defFr:"Volume de sol influencé par les racines : hotspot d'activité biologique et biogéochimique.",
    defEn:"The zone of soil shaped by roots — a hotspot of biological and biogeochemical activity.",
    subs:[ ["Exsudats racinaires","Root exudates"], ["Priming effect","Priming effect"],
           ["Bactéries promotrices","PGPR"], ["Interactions multi-trophiques","Multi-trophic interactions"] ],
    neighbors:["microbio","fungi","plant-nutrition","roots","edaphology"] },

  /* ====================== Z6 — SOLS & PLANTES (ÉDAPHOLOGIE) ====================== */
  { id:"edaphology", zone:"z6",
    fr:"Édaphologie", en:"Edaphology",
    defFr:"Le sol vu comme milieu de vie des plantes — l'autre grande branche de la science des sols, complémentaire à la pédologie <em>s.s.</em>",
    defEn:"Soil as a plant-growth medium — the other great branch of soil science, complementary to pedology <em>s.s.</em>",
    subs:[ ["Habitats édaphiques","Edaphic habitats"], ["Edaphisme","Edaphism"],
           ["Autoecologie des sols","Soil autecology"] ],
    neighbors:["plant-nutrition","fertility","roots","spac"] },
  { id:"plant-nutrition", zone:"z6",
    fr:"Nutrition minérale des plantes", en:"Plant mineral nutrition",
    defFr:"Prélèvement racinaire des macro- et micro-éléments : N, P, K, Ca, Mg, S, micronutriments.",
    defEn:"Root uptake of macro- and micro-nutrients: N, P, K, Ca, Mg, S and micronutrients.",
    subs:[ ["Macroéléments","Macronutrients"], ["Micronutriments","Micronutrients"],
           ["Carences &amp; toxicités","Deficiencies &amp; toxicities"] ],
    neighbors:["edaphology","fertility","rhizosphere","acidity"] },
  { id:"fertility", zone:"z6",
    fr:"Fertilité des sols", en:"Soil fertility",
    defFr:"Capacité du sol à fournir les nutriments dans l'espace et le temps — propriétés physiques, chimiques et biologiques conjuguées.",
    defEn:"The soil's capacity to supply nutrients in space and time — combining physical, chemical and biological properties.",
    subs:[ ["Indicateurs de fertilité","Fertility indicators"], ["Diagnostic de fertilité","Fertility diagnostics"],
           ["Fertilité physique / chimique / biologique","Physical / chemical / biological fertility"] ],
    neighbors:["plant-nutrition","som","fertilization","health","agri-soils"] },
  { id:"roots", zone:"z6",
    fr:"Architecture racinaire", en:"Root architecture",
    defFr:"Morphologie, profondeur et plasticité des systèmes racinaires — interface entre plante et sol.",
    defEn:"Morphology, depth and plasticity of root systems — the plant-soil interface.",
    subs:[ ["Phénotypage racinaire","Root phenotyping"], ["Profondeur d'enracinement","Rooting depth"],
           ["Plasticité","Plasticity"] ],
    neighbors:["rhizosphere","edaphology","spac","structure"] },
  { id:"symbioses", zone:"z6",
    fr:"Symbioses plantes-microorganismes", en:"Plant-microbe symbioses",
    defFr:"Mycorhizes, rhizobiums, endophytes, PGPR : partenariats microbiens au service de la plante.",
    defEn:"Mycorrhizae, rhizobia, endophytes, PGPR: microbial partnerships that work for the plant.",
    subs:[ ["Mycorhizes","Mycorrhizae"], ["Fixation symbiotique N₂","Symbiotic N₂ fixation"],
           ["Endophytes","Endophytes"] ],
    neighbors:["fungi","microbio","rhizosphere","plant-nutrition"] },
  { id:"spac", zone:"z6",
    fr:"Continuum sol-plante-atmosphère (SPAC)", en:"Soil-plant-atmosphere continuum (SPAC)",
    defFr:"Cadre physiologique couplant transpiration, potentiel hydrique et transferts — base de l'agro-hydrologie.",
    defEn:"Physiological framework coupling transpiration, water potential and fluxes — foundation of agro-hydrology.",
    subs:[ ["Potentiel hydrique","Water potential"], ["Transpiration","Transpiration"],
           ["Stress hydrique","Water stress"], ["Redistribution hydraulique","Hydraulic redistribution"] ],
    neighbors:["retention","hydrology","plant-nutrition","irrigation","climate-feedback"] },
  { id:"fertilization", zone:"z6",
    fr:"Fertilisation &amp; amendements", en:"Fertilization &amp; amendments",
    defFr:"Diagnostic nutritif, apports minéraux et organiques, amendements calciques et organiques.",
    defEn:"Nutrient diagnostics, mineral and organic inputs, liming and organic amendments.",
    subs:[ ["Engrais minéraux","Mineral fertilizers"], ["Amendements organiques","Organic amendments"],
           ["Chaulage","Liming"], ["Biochar","Biochar"] ],
    neighbors:["fertility","plant-nutrition","acidity","som","agri-soils"] },

  /* ====================== Z7 — GESTION & USAGE DES SOLS ====================== */
  { id:"agri-soils", zone:"z7",
    fr:"Sols agricoles", en:"Agricultural soils",
    defFr:"Sols cultivés : enjeux de fertilité, travail, rotations, agro-écologie, couverts.",
    defEn:"Cultivated soils: fertility, tillage, rotations, agro-ecology, cover crops.",
    subs:[ ["Grandes cultures","Arable soils"], ["Viticulture","Viticulture soils"],
           ["Cultures pérennes","Perennial crops"], ["Agroécologie","Agro-ecology"] ],
    neighbors:["fertility","tillage","cover-crops","health","erosion"] },
  { id:"forest-soils", zone:"z7",
    fr:"Sols forestiers", en:"Forest soils",
    defFr:"Sols sous couvert forestier : humus, litière, cycles lents, nutrition des peuplements.",
    defEn:"Soils under forest cover: humus forms, litter, slow cycles, stand nutrition.",
    subs:[ ["Formes d'humus","Humus forms"], ["Litière","Litter"],
           ["Nutrition forestière","Forest nutrition"] ],
    neighbors:["ecology","som","fungi","pedogenic-processes"] },
  { id:"grasslands", zone:"z7",
    fr:"Prairies &amp; pastoralisme", en:"Grasslands &amp; rangelands",
    defFr:"Sols de prairies permanentes et pastorales : séquestration de C, compaction par le pâturage.",
    defEn:"Permanent-grassland and rangeland soils: C sequestration, grazing-induced compaction.",
    subs:[ ["Pâturage","Grazing"], ["Prairies permanentes","Permanent grasslands"] ],
    neighbors:["som","structure","carbon-climate","agri-soils"] },
  { id:"tillage", zone:"z7",
    fr:"Travail du sol", en:"Tillage systems",
    defFr:"Labour, travail réduit, semis direct, agriculture de conservation — et leurs conséquences sur la structure et la vie du sol.",
    defEn:"Plough, reduced tillage, no-till, conservation agriculture — and their effects on structure and soil life.",
    subs:[ ["Labour","Ploughing"], ["Travail réduit","Reduced tillage"], ["Semis direct","No-till"],
           ["Agriculture de conservation","Conservation agriculture"] ],
    neighbors:["structure","mechanics","cover-crops","health","erosion"] },
  { id:"cover-crops", zone:"z7",
    fr:"Couverts &amp; rotations", en:"Cover crops &amp; rotations",
    defFr:"Cultures intermédiaires, rotations longues, intercultures — restitutions organiques et protection des sols.",
    defEn:"Cover crops, long rotations and inter-cropping — organic returns and soil protection.",
    subs:[ ["Cultures intermédiaires","Cover crops"], ["Rotations","Rotations"],
           ["Engrais verts","Green manures"] ],
    neighbors:["agri-soils","tillage","som","fertility"] },
  { id:"irrigation", zone:"z7",
    fr:"Irrigation &amp; gestion de l'eau", en:"Irrigation &amp; water management",
    defFr:"Techniques d'irrigation, drainage, gestion des eaux usées et saline — un levier majeur et risqué.",
    defEn:"Irrigation and drainage techniques, wastewater and saline water management — a powerful yet risky lever.",
    subs:[ ["Irrigation gravitaire","Surface irrigation"], ["Micro-irrigation","Micro-irrigation"],
           ["Irrigation saline","Saline irrigation"], ["Drainage","Drainage"] ],
    neighbors:["hydrology","salinity","spac","agri-soils"] },
  { id:"agroforestry", zone:"z7",
    fr:"Agroforesterie", en:"Agroforestry",
    defFr:"Association d'arbres et de cultures/élevage — effets sur structure, MO, biodiversité et microclimat du sol.",
    defEn:"Integrating trees with crops and livestock — effects on structure, SOM, biodiversity and soil microclimate.",
    subs:[ ["Agroforesterie tempérée","Temperate agroforestry"], ["Systèmes agroforestiers tropicaux","Tropical agroforestry"] ],
    neighbors:["agri-soils","forest-soils","som","biodiversity"] },
  { id:"conservation", zone:"z7",
    fr:"Conservation &amp; restauration", en:"Conservation &amp; restoration",
    defFr:"Pratiques, politiques et techniques de protection, restauration et réhabilitation des sols dégradés.",
    defEn:"Practices, policies and techniques for protecting, restoring and rehabilitating degraded soils.",
    subs:[ ["Lutte antiérosive","Erosion control"], ["Restauration des sols","Soil restoration"],
           ["Réhabilitation de sites","Site rehabilitation"] ],
    neighbors:["erosion","degradation","health","law","remediation"] },

  /* ====================== Z8 — SOLS ANTHROPOGÉNIQUES ====================== */
  { id:"urban-soils", zone:"z8",
    fr:"Sols urbains (SUITMA)", en:"Urban soils (SUITMA)",
    defFr:"Cadre SUITMA (urbains, industriels, transports, miniers, militaires) — sols souvent fabriqués ou profondément remaniés.",
    defEn:"SUITMA framework (Urban, Industrial, Traffic, Mining, Military soils) — often man-made or deeply reworked.",
    subs:[ ["Parcs &amp; jardins urbains","Urban parks"], ["Remblais","Artificial fill"],
           ["Services écosystémiques urbains","Urban ecosystem services"] ],
    neighbors:["technosols","sealing","anthropogenesis","geotech","contamination"] },
  { id:"technosols", zone:"z8",
    fr:"Technosols", en:"Technosols",
    defFr:"Sols artificiels dominés par des matériaux anthropiques — gravats, mâchefers, déchets miniers, substrats reconstitués.",
    defEn:"Artificial soils dominated by human-made materials — rubble, slag, mine waste, engineered substrates.",
    subs:[ ["Mâchefers","Slag / bottom ash"], ["Sédiments pollués","Contaminated sediments"],
           ["Substrats construits","Engineered substrates"] ],
    neighbors:["urban-soils","mining-soils","anthropogenesis","remediation"] },
  { id:"mining-soils", zone:"z8",
    fr:"Sols miniers &amp; post-miniers", en:"Mining &amp; post-mining soils",
    defFr:"Sols très perturbés par l'extraction : stériles, verses, bassins, drainage minier acide — enjeux de restauration majeurs.",
    defEn:"Soils profoundly disturbed by extraction: tailings, dumps, ponds, acid mine drainage — major restoration challenges.",
    subs:[ ["Drainage minier acide","Acid mine drainage"], ["Stériles","Tailings"],
           ["Restauration minière","Mine restoration"] ],
    neighbors:["technosols","remediation","metals","contamination"] },
  { id:"contamination", zone:"z8",
    fr:"Sols contaminés", en:"Contaminated soils",
    defFr:"Pollutions métalliques, organiques et radioactives : diagnostic, modélisation et gestion des risques.",
    defEn:"Metal, organic and radioactive contamination: diagnostics, modelling and risk management.",
    subs:[ ["Métaux &amp; ETM","Metals &amp; trace elements"], ["Polluants organiques","Organic pollutants"],
           ["Radionucléides","Radionuclides"], ["Évaluation des risques","Risk assessment"] ],
    neighbors:["metals","remediation","mining-soils","technosols"] },
  { id:"remediation", zone:"z8",
    fr:"Dépollution &amp; remédiation", en:"Remediation",
    defFr:"Techniques de traitement in situ ou ex situ : physico-chimique, biologique, phyto-/myco-remédiation.",
    defEn:"In-situ or ex-situ treatment techniques: physico-chemical, biological, phyto- and myco-remediation.",
    subs:[ ["Phytoremédiation","Phytoremediation"], ["Bioremédiation","Bioremediation"],
           ["Lavage / stabilisation","Washing / stabilisation"] ],
    neighbors:["contamination","metals","mining-soils","technosols","conservation"] },
  { id:"sealing", zone:"z8",
    fr:"Artificialisation &amp; imperméabilisation", en:"Soil sealing &amp; artificialisation",
    defFr:"Scellement des sols par bâtiments et infrastructures — perte de fonctions, enjeu « zéro artificialisation nette ».",
    defEn:"Soil sealing by buildings and infrastructure — loss of soil functions, at the heart of \"net zero soil sealing\".",
    subs:[ ["ZAN (« zéro artificialisation nette »)","Net-zero soil sealing"], ["Imperméabilisation","Sealing"],
           ["Pertes de services","Loss of services"] ],
    neighbors:["urban-soils","law","ecosystem-services","degradation"] },
  { id:"geotech", zone:"z8",
    fr:"Géotechnique &amp; génie civil", en:"Geotechnics &amp; civil engineering",
    defFr:"Mécanique des sols au sens ingénieur : fondations, terrassements, stabilité des pentes, ouvrages en terre.",
    defEn:"Soil mechanics in the engineering sense: foundations, earthworks, slope stability, earthworks design.",
    subs:[ ["Fondations","Foundations"], ["Terrassements","Earthworks"],
           ["Stabilité des pentes","Slope stability"], ["Barrages &amp; digues","Dams &amp; dykes"] ],
    neighbors:["mechanics","shrink-swell","urban-soils","sealing"] },
  { id:"forensics", zone:"z8",
    fr:"Criminalistique des sols", en:"Soil forensics",
    defFr:"Identification et traçabilité de traces de sol dans les enquêtes criminelles — provenance et comparaison d'échantillons.",
    defEn:"Identification and tracing of soil traces in criminal investigations — provenance and sample comparison.",
    subs:[ ["Comparaison d'échantillons","Sample comparison"], ["Provenance","Provenance"],
           ["Signatures géochimiques","Geochemical fingerprints"] ],
    neighbors:["mineralogy","metals","archaeology"] },

  /* ====================== Z9 — ENVIRONNEMENT & CLIMAT ====================== */
  { id:"wetlands", zone:"z9",
    fr:"Sols hydromorphes &amp; zones humides", en:"Wetland &amp; hydric soils",
    defFr:"Sols saturés : tourbe, gley, pseudogley ; processus anaérobies et stockage massif de C.",
    defEn:"Saturated soils: peat, gley, pseudogley; anaerobic processes and massive C storage.",
    subs:[ ["Tourbières","Peatlands"], ["Gley &amp; pseudogley","Gley &amp; pseudogley"],
           ["Hydromorphie","Hydromorphy"] ],
    neighbors:["redox","aeration","carbon-climate","hydrology","ecosystem-services"] },
  { id:"alluvial", zone:"z9",
    fr:"Sols alluvionnaires &amp; fluviatiles", en:"Alluvial &amp; fluvial soils",
    defFr:"Sols de plaines alluviales et de ripisylves — dépôts stratifiés, inondabilité, stockage de C.",
    defEn:"Soils of alluvial plains and riparian forests — stratified deposits, flood dynamics, C storage.",
    subs:[ ["Ripisylves","Riparian forests"], ["Alluvions","Alluvium"], ["Zones d'expansion de crue","Flood expansion zones"] ],
    neighbors:["wetlands","hydrology","pedogenic-processes"] },
  { id:"subaqueous", zone:"z9",
    fr:"Sols submergés &amp; marins", en:"Subaqueous &amp; marine soils",
    defFr:"Sols sous la nappe, lagunes, vasières, prés salés — une frontière jeune de la pédologie.",
    defEn:"Soils beneath the water table, lagoons, tidal flats and salt marshes — a young frontier of pedology.",
    subs:[ ["Sols subaquatiques","Subaqueous soils"], ["Prés salés","Salt marshes"], ["Vasières","Tidal flats"] ],
    neighbors:["wetlands","salinity","pedogenic-processes"] },
  { id:"cryosols", zone:"z9",
    fr:"Cryosols &amp; pergélisol", en:"Cryosols &amp; permafrost",
    defFr:"Sols gelés en permanence — stocks énormes de C et de CH₄, hyper-sensibles au réchauffement.",
    defEn:"Permanently frozen soils — huge stocks of C and CH₄, highly sensitive to warming.",
    subs:[ ["Permafrost","Permafrost"], ["Couche active","Active layer"], ["Dégel","Thaw"] ],
    neighbors:["thermal","carbon-climate","climate-feedback"] },
  { id:"salinity", zone:"z9",
    fr:"Salinité &amp; sodicité", en:"Soil salinity &amp; sodicity",
    defFr:"Accumulation de sels solubles et de sodium échangeable — facteur mondial majeur de dégradation, notamment sous irrigation.",
    defEn:"Accumulation of soluble salts and exchangeable sodium — a leading global degradation driver, especially under irrigation.",
    subs:[ ["Salinisation primaire","Primary salinisation"], ["Salinisation secondaire","Secondary salinisation"],
           ["Sols sodiques","Sodic soils"] ],
    neighbors:["irrigation","degradation","remote-sensing","chemistry"] },
  { id:"erosion", zone:"z9",
    fr:"Érosion &amp; désertification", en:"Erosion &amp; desertification",
    defFr:"Érosion hydrique, éolienne, gravitaire ; désertification dans les zones arides et semi-arides.",
    defEn:"Water, wind and gravity erosion; desertification in arid and semi-arid regions.",
    subs:[ ["Érosion hydrique","Water erosion"], ["Érosion éolienne","Wind erosion"],
           ["Glissements de terrain","Landslides"], ["Désertification","Desertification"] ],
    neighbors:["degradation","conservation","soil-evolution","tillage"] },
  { id:"degradation", zone:"z9",
    fr:"Dégradation des sols", en:"Soil degradation",
    defFr:"Pertes physiques, chimiques et biologiques de qualité des sols — érosion, tassement, pertes de MO, contamination.",
    defEn:"Physical, chemical and biological loss of soil quality — erosion, compaction, SOM loss, contamination.",
    subs:[ ["Tassement","Compaction"], ["Perte de MO","SOM loss"], ["Contamination","Contamination"],
           ["Battance","Crusting"] ],
    neighbors:["erosion","sealing","contamination","health","conservation"] },
  { id:"carbon-climate", zone:"z9",
    fr:"Séquestration du C &amp; climat", en:"Soil carbon &amp; climate",
    defFr:"Stockage et émissions de carbone par les sols — initiative 4‰, stratégies de séquestration, rétroactions climatiques.",
    defEn:"Soil carbon storage and emissions — the 4 per 1000 initiative, sequestration strategies, climate feedbacks.",
    subs:[ ["Initiative 4‰","4 per 1000 initiative"], ["Stocks de C","Soil C stocks"],
           ["Émissions GES","GHG emissions"], ["Rétroactions climatiques","Climate feedbacks"] ],
    neighbors:["som","biogeochem","cryosols","wetlands","climate-feedback"] },
  { id:"critical-zone", zone:"z9",
    fr:"Zone critique", en:"Critical zone science",
    defFr:"« Peau vivante » de la Terre, du sommet des canopées à la roche-mère fracturée : intégration de la pédologie, géochimie, hydrologie et écologie.",
    defEn:"Earth's \"living skin\", from canopy to weathered bedrock — integrating pedology, geochemistry, hydrology and ecology.",
    subs:[ ["CZO / Observatoires","Critical Zone Observatories"], ["Saprolite","Saprolite"],
           ["Bedrock fracturé","Weathered bedrock"] ],
    neighbors:["weathering","soil-evolution","biogeochem","hydrology","ecosystem-services"] },
  { id:"ecosystem-services", zone:"z9",
    fr:"Services écosystémiques", en:"Ecosystem services",
    defFr:"Services de régulation, approvisionnement, culturels et de support rendus par les sols.",
    defEn:"Regulating, provisioning, cultural and supporting services delivered by soils.",
    subs:[ ["Régulation du climat","Climate regulation"], ["Épuration de l'eau","Water purification"],
           ["Support de biodiversité","Biodiversity support"], ["Patrimoine","Cultural heritage"] ],
    neighbors:["biodiversity","biogeochem","carbon-climate","health","soil-security"] },
  { id:"climate-feedback", zone:"z9",
    fr:"Rétroactions sol-climat", en:"Soil-climate feedbacks",
    defFr:"Couplages entre sol et climat : albédo, humidité, vapeur d'eau, émissions de GES — cible de la modélisation du système Terre.",
    defEn:"Soil-climate coupling: albedo, moisture, water vapour and GHG fluxes — a central target of Earth-system modelling.",
    subs:[ ["Albédo","Albedo"], ["Humidité des sols","Soil moisture"], ["Vapeur d'eau","Water vapour"] ],
    neighbors:["thermal","spac","carbon-climate","cryosols"] },

  /* ====================== Z10 — SOCIÉTÉ & FRONTIÈRES ====================== */
  { id:"history", zone:"z10",
    fr:"Histoire &amp; épistémologie", en:"History &amp; epistemology",
    defFr:"Des pionniers (Dokuchaev, Müller, Jenny, Duchaufour) à la science contemporaine — comment la discipline s'est construite.",
    defEn:"From the pioneers (Dokuchaev, Müller, Jenny, Duchaufour) to contemporary science — how the discipline was built.",
    subs:[ ["Dokuchaev","Dokuchaev"], ["École française","French school"],
           ["Épistémologie","Epistemology"] ],
    neighbors:["education","ethnopedology","classification"] },
  { id:"education", zone:"z10",
    fr:"Enseignement &amp; médiation", en:"Education &amp; outreach",
    defFr:"Pédagogie des sols, vulgarisation, médiation scientifique, citoyenneté des sols.",
    defEn:"Pedagogy, outreach, science communication and soil citizenship.",
    subs:[ ["Pédagogie","Pedagogy"], ["Vulgarisation","Science communication"],
           ["Sciences participatives","Citizen science"] ],
    neighbors:["history","health","law","soil-security"] },
  { id:"ethnopedology", zone:"z10",
    fr:"Ethnopédologie", en:"Ethnopedology",
    defFr:"Comment différentes cultures décrivent, classent et gèrent leurs sols — savoirs vernaculaires et locaux.",
    defEn:"How different cultures describe, classify and manage their soils — vernacular and local knowledge.",
    subs:[ ["Savoirs locaux","Local knowledge"], ["Classifications vernaculaires","Vernacular classifications"],
           ["Gestion traditionnelle","Traditional management"] ],
    neighbors:["classification","history","soil-security","education"] },
  { id:"law", zone:"z10",
    fr:"Droit &amp; gouvernance des sols", en:"Soil law &amp; governance",
    defFr:"Statut juridique des sols, politiques publiques, directives européennes, instruments de protection.",
    defEn:"Legal status, public policy, European directives and soil-protection instruments.",
    subs:[ ["Droit français des sols","French soil law"], ["Directive UE","EU soil directive"],
           ["ZAN","Net-zero soil sealing"], ["Sites &amp; sols pollués","Contaminated-site law"] ],
    neighbors:["sealing","conservation","soil-security","education"] },
  { id:"soil-security", zone:"z10",
    fr:"Sécurité des sols", en:"Soil security",
    defFr:"Cadre intégrateur (Capability, Condition, Capital, Connectivity, Codification) pour relier sol, alimentation, climat, biodiversité.",
    defEn:"An integrative framework (Capability, Condition, Capital, Connectivity, Codification) linking soil to food, climate and biodiversity.",
    subs:[ ["Capability / Condition","Capability / Condition"], ["Capital / Connectivity","Capital / Connectivity"],
           ["Codification","Codification"], ["ODD / SDGs","Sustainable Development Goals"] ],
    neighbors:["law","health","ecosystem-services","one-health","carbon-climate"] },
  { id:"health", zone:"z10",
    fr:"Santé des sols", en:"Soil health",
    defFr:"Capacité durable d'un sol à fonctionner — cadre opérationnel mêlant indicateurs physiques, chimiques, biologiques.",
    defEn:"A soil's sustained capacity to function — an operational framework mixing physical, chemical and biological indicators.",
    subs:[ ["Indicateurs","Indicators"], ["Bio-indicateurs","Bio-indicators"],
           ["Scoring","Scoring methods"], ["Loi UE Soil Monitoring","EU Soil Monitoring Law"] ],
    neighbors:["biodiversity","som","soil-security","one-health","fertility"] },
  { id:"one-health", zone:"z10",
    fr:"One Health / Planetary Health", en:"One Health / Planetary Health",
    defFr:"Reconnaître la santé des sols comme maillon des santés humaine, animale, végétale et environnementale.",
    defEn:"Placing soil health as a core link in human, animal, plant and environmental health.",
    subs:[ ["Santé humaine","Human health"], ["Résistances antibiotiques","Antimicrobial resistance"],
           ["Pathogènes","Pathogens"] ],
    neighbors:["health","biodiversity","contamination","soil-security"] },
  { id:"archaeology", zone:"z10",
    fr:"Géoarchéologie &amp; archéopédologie", en:"Geoarchaeology &amp; archaeopedology",
    defFr:"Le sol comme archive : paléosols, anthroposols, stratigraphie, diagnostic archéologique.",
    defEn:"Soil as archive: paleosols, anthrosols, stratigraphy, archaeological diagnostics.",
    subs:[ ["Paléosols","Paleosols"], ["Sols anthropiques anciens","Ancient anthrosols"],
           ["Géoarchéologie","Geoarchaeology"] ],
    neighbors:["paleopedology","anthropogenesis","micromorphology","forensics"] },
  { id:"extraterrestrial", zone:"z10",
    fr:"Pédologie extra-terrestre", en:"Extraterrestrial pedology",
    defFr:"Régolithes lunaires et martiens, astéroïdes, Titan… Qu'est-ce qu'un « sol » hors-Terre ? 🌕 🪐",
    defEn:"Lunar and Martian regoliths, asteroids, Titan… What is a \"soil\" off Earth? 🌕 🪐",
    subs:[ ["Régolithe lunaire","Lunar regolith"], ["Sols martiens","Martian soils"],
           ["Astéroïdes &amp; comètes","Asteroids &amp; comets"] ],
    neighbors:["mineralogy","pedogenic-processes","weathering"] },
];

/* -----------------------------------------------------------------------------
   BRIDGE THEMES — cross-cutting concepts that light up subsets of nodes
   ---------------------------------------------------------------------------*/
const BRIDGES = [
  { id:"carbon-climate-theme", fr:"Carbone du sol &amp; climat", en:"Soil carbon &amp; climate",
    descFr:"Du stockage moléculaire de la MO aux rétroactions globales — tous les nœuds où le C du sol compte.",
    descEn:"From molecular SOM storage to global feedbacks — every node where soil C matters.",
    nodes:["som","biogeochem","carbon-climate","cryosols","wetlands","agroforestry","cover-crops","grasslands","climate-feedback","conservation","forest-soils"] },
  { id:"spac-theme", fr:"Continuum sol-plante-eau", en:"Soil-plant-water continuum",
    descFr:"L'eau du sol jusqu'à l'atmosphère, via les racines.",
    descEn:"Water from soil to atmosphere, through roots.",
    nodes:["hydrology","retention","spac","plant-nutrition","roots","irrigation","edaphology","rhizosphere"] },
  { id:"critical-zone-theme", fr:"Zone critique", en:"Critical Zone science",
    descFr:"Peau vivante de la Terre : altération, eaux, vivants, sol.",
    descEn:"Earth's living skin: weathering, waters, biota, soil.",
    nodes:["factors","weathering","pedogenic-processes","soil-evolution","hydrology","biogeochem","critical-zone","ecosystem-services"] },
  { id:"soil-security-theme", fr:"Sécurité des sols", en:"Soil Security",
    descFr:"Cadre intégrateur : 5 C reliant sol, alimentation et climat.",
    descEn:"Integrative 5C framework linking soil, food and climate.",
    nodes:["soil-security","law","health","education","ecosystem-services","dsm","carbon-climate","one-health"] },
  { id:"dsm-theme", fr:"Évaluation numérique des sols", en:"Digital soil assessment &amp; pedometrics",
    descFr:"Modèles, données, télédétection, apprentissage machine.",
    descEn:"Models, data, remote sensing, machine learning.",
    nodes:["dsm","pedometrics","remote-sensing","modeling","cartography","survey","metrology"] },
  { id:"governance-theme", fr:"Gouvernance &amp; politiques des sols", en:"Soil governance &amp; policy",
    descFr:"Droit, politiques, suivi et protection des sols.",
    descEn:"Law, policy, monitoring and protection of soils.",
    nodes:["law","soil-security","health","sealing","conservation","education","one-health"] },
  { id:"ethnopedology-theme", fr:"Savoirs locaux &amp; ethnopédologie", en:"Local knowledge &amp; ethnopedology",
    descFr:"Comment les cultures perçoivent, nomment et gèrent leurs sols.",
    descEn:"How cultures perceive, name and manage their soils.",
    nodes:["ethnopedology","classification","history","education","agroforestry","soil-security"] },
  { id:"risk-theme", fr:"Risques &amp; contaminations", en:"Risk &amp; contamination",
    descFr:"Des polluants aux aléas géotechniques et pathogènes.",
    descEn:"From pollutants to geotechnical hazards and pathogens.",
    nodes:["contamination","metals","remediation","mining-soils","technosols","shrink-swell","geotech","one-health","forensics"] },
];

/* -----------------------------------------------------------------------------
   Placeholders — a couple of extra "synthetic" nodes referenced as neighbors
   but not rendered as chips (keeps links working without visual clutter)
   ---------------------------------------------------------------------------*/
const PLACEHOLDERS = {
  "acid-soils": { fr:"Sols acides", en:"Acid soils" },
  "mapping-dsm": { fr:"Cartographie numérique", en:"Digital soil mapping" },
  "modeling": { fr:"Modélisation des sols", en:"Soil process modeling" },
  "metrology": { fr:"Métrologie &amp; analyses", en:"Soil analytics &amp; metrology" },
};


// --- exported for other scripts ---
window.ZONES = ZONES;
window.NODES = NODES;
window.BRIDGES = BRIDGES;
window.PLACEHOLDERS = PLACEHOLDERS;
